apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-nginx
spec:
  selector:
    matchLabels:
      app: sample-nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: sample-nginx
    spec:
      containers:
      - name: sample-nginx-cont
        image: spc35771/examples-nginx:latest
        ports:
        - name: 8080-tcp
          containerPort: 8080
