---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: sample-nginx-inter-dc
  labels:
    router: inter-dc
spec:
  host: your-hostname.apps.inter-dc.okd4.teh-1.snappcloud.io
  port:
    targetPort: web
  to:
    name: sample-nginx
  tls:
    termination: edge # passthrough reencrypt
    insecureEdgeTerminationPolicy: Redirect # None Allow
