---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: sample-nginx-private
  labels:
    router: private
spec:
  host: your-hostname.apps.private.okd4.teh-1.snappcloud.io
  port:
    targetPort: web
  to:
    name: sample-nginx


