apiVersion: apps/v1
kind: Deployment
metadata:
  name: no-pod-permission
spec:
  selector:
    matchLabels:
      app: sample-nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: sample-nginx
    spec:
      containers:
      - name: sample-nginx-cont
        image: spc35771/examples-nginx:latest
        ports:
        - name: web
          containerPort: 8080
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
