apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-pull-back-off
spec:
  selector:
    matchLabels:
      app: sample-nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: sample-nginx
    spec:
      containers:
      - name: sample-nginx-cont
        image: spc35771/examples-nginnnnx:latest
        ports:
        - name: web
          containerPort: 8080
