apiVersion: apps/v1
kind: Deployment
metadata:
  name: create-container-error
spec:
  selector:
    matchLabels:
      app: sample-nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: sample-nginx
    spec:
      containers:
      - name: sample-nginx-cont
        image: alpine
        command:
          - "/bin/bash"
          - "-c"
          - |
            ehco Hi
        ports:
        - name: web
          containerPort: 8080
