apiVersion: apps/v1
kind: Deployment
metadata:
  name: not-ready
spec:
  selector:
    matchLabels:
      app: sample-nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: sample-nginx
    spec:
      containers:
      - name: sample-nginx-cont
        image: spc35771/examples-nginx:latest
        ports:
        - name: web
          containerPort: 8080
        readinessProbe:
          httpGet:
            path: /ready
            port: web
