apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc
  namespace: <your-namespace>
spec:
  storageClassName: block-storage-standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "1Gi"
