apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-nginx
spec:
  selector:
    matchLabels:
      app: sample-nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: sample-nginx
    spec:
      containers:
      - name: sample-nginx-cont
        image: spc35771/examples-nginx:latest
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
