apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sample-nginx-sts
spec:
  selector:
    matchLabels:
      app: sample-nginx-sts
  replicas: 1
  template:
    metadata:
      labels:
        app: sample-nginx-sts
    spec:
      containers:
      - name: sample-nginx-cont
        image: spc35771/examples-nginx:latest
        ports:
        - name: web
          containerPort: 8080
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
