apiVersion: apps/v1
kind: Deployment
metadata:
  name: type-a
spec:
  selector:
    matchLabels:
      app: prometheus
  replicas: 1
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: prometheus/prometheus:latest
        ports:
        - name: web
          containerPort: 8080
